/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Programa");
  lbl_id = new GLabel(this, 20, 20, 50, 20);
  lbl_id.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_id.setText("ID");
  lbl_id.setOpaque(false);
  lbl_fecha = new GLabel(this, 20, 50, 50, 20);
  lbl_fecha.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_fecha.setText("Fecha");
  lbl_fecha.setOpaque(false);
  lblFechaActual = new GLabel(this, 80, 50, 80, 20);
  lblFechaActual.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblFechaActual.setOpaque(false);
  chkAleatorio = new GCheckbox(this, 20, 80, 120, 20);
  chkAleatorio.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  chkAleatorio.setText("Aleatorio");
  chkAleatorio.setOpaque(false);
  lblNotas = new GLabel(this, 170, 20, 80, 20);
  lblNotas.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblNotas.setText("Notas");
  lblNotas.setOpaque(false);
  txaNotas = new GTextArea(this, 250, 20, 330, 80, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  txaNotas.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel lbl_id; 
GLabel lbl_fecha; 
GLabel lblFechaActual; 
GCheckbox chkAleatorio; 
GLabel lblNotas; 
GTextArea txaNotas; 
